apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /opt/kind_volumes/kafka-0
    containerPath: /var/lib/kafka
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 31321
    hostPort: 31321
  - containerPort: 31300
    hostPort: 31300
- role: worker
  extraMounts:
  - hostPath: /opt/kind_volumes/kafka-1
    containerPath: /var/lib/kafka
- role: worker
  extraMounts:
  - hostPath: /opt/kind_volumes/kafka-2
    containerPath: /var/lib/kafka
